# Generated by Django 2.2.10 on 2020-03-15 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.TextField()),
                ('publisher', models.TextField()),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField(default=models.FloatField())),
                ('condition', models.CharField(choices=[('VG', 'Very Good'), ('G', 'Good'), ('M', 'Medium'), ('B', 'Bad'), ('VB', 'very bad')], max_length=2)),
                ('category', models.CharField(choices=[('C', 'Chemistry'), ('B', 'Biology'), ('E', 'English'), ('G', 'Geography'), ('M', 'Math'), ('O', 'Other'), ('P', 'Polish'), ('Ph', 'Physic')], max_length=2)),
                ('label', models.CharField(choices=[('S', 'success'), ('I', 'info'), ('D', 'danger')], max_length=1)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('numbers_of_entries', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OrderBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('books', models.ManyToManyField(to='core.OrderBook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
