# Generated by Django 2.2.10 on 2020-03-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('C', 'Chemistry'), ('B', 'Biology'), ('E', 'English'), ('G', 'Geography'), ('M', 'Math'), ('O', 'Other'), ('P', 'Polish'), ('Ph', 'Physic')], default='O', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], default='P', max_length=1),
            preserve_default=False,
        ),
    ]
