# Generated by Django 2.2.10 on 2020-03-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='original_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
