# Generated by Django 2.2.10 on 2020-03-16 11:37

import core.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200315_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default=core.models.random_img, upload_to='project_pics'),
        ),
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2020, 3, 16, 11, 37, 39, 960137, tzinfo=utc)),
        ),
    ]
