# Generated by Django 2.2.10 on 2020-03-16 16:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200316_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2020, 3, 16, 16, 13, 8, 963350, tzinfo=utc)),
        ),
    ]
