# Generated by Django 2.2.10 on 2020-03-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200314_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default='2020-03-14'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='numbers_of_entries',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='label',
            field=models.CharField(choices=[('S', 'success'), ('I', 'info'), ('D', 'danger')], max_length=1),
        ),
    ]
