# Generated by Django 2.2.10 on 2020-03-14 15:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200314_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.TextField(default='2020-03-14'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='condition',
            field=models.CharField(choices=[('VG', 'Very Good'), ('G', 'Good'), ('M', 'Medium'), ('B', 'Bad'), ('VB', 'very bad')], default='2020-03-14', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
