# Generated by Django 2.2.10 on 2020-03-14 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200314_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='original_price',
            new_name='discount_price',
        ),
    ]
