# Generated by Django 2.2.10 on 2020-03-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200314_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='discount_price',
            field=models.FloatField(default=models.FloatField(default=0)),
        ),
    ]
