# Generated by Django 2.2.10 on 2020-03-28 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20200326_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='amount',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='photo',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='books.Book'),
        ),
    ]
